# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4aefe6ac3c62f97ea38d5c689c961133a83d927aad19b31f75ec3dff7abb73ee3fe0080f4575b6279511bca4ef83a8eb54a7d97f2962fed1b7693b415605c77

test:
  secret_key_base: b801fc308ce4a4f465a5abcbc38b2d507e29bf744edd4c7f1542f4f55217ec54f190fe56a772bc0e280e252d183727cc6b8bc48ac758ffea6e4c037f4f6ce16f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
